### --- AUTHENTICATION ---

### Register Entreprise + User
POST {{baseUrl}}/api/auth/register-entreprise
Content-Type: application/json

{
  "name": "Bob",
  "surname": "Leroi",
  "mail": "lenny.loy@gmail.com",
  "password": "Password123!",
  "nomEntreprise": "TrueCodeMinds Inc."
}

### Login et récupération automatique du Token
POST {{baseUrl}}/api/auth/login-entreprise
Content-Type: application/json

{
  "mail": "lenny.loy@gmail.com",
  "password": "Password123!"
}

> {%
    client.global.set("authToken", response.body);
    client.log("✅ Token texte brut capturé avec succès !");
    client.log("Valeur : " + client.global.get("authToken"));
%}

### --- PARKING ---

### Ajouter un Parking
POST {{baseUrl}}/api/parking/addParking
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Parking Sud",
  "description": "Un peu gluant mais appetissant",
  "linkMaps": "http://google.com/maps/1",
  "entrepriseId": 1
}

### Récupérer tous les parkings
GET {{baseUrl}}/api/parking/getAllParking
Authorization: Bearer {{authToken}}
Accept: application/json
Cache-Control: no-cache

### Supprimer un parking (Exemple ID 2)
DELETE {{baseUrl}}/api/parking/deleteParking/3
Authorization: Bearer {{authToken}}

### --- PLACES ---

### Générer des places pour un parking
POST {{baseUrl}}/api/place/generer
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "parkingId": 4,
  "quantite": 15,
  "tarifJournalier": 15,
  "tarifAnnuel":200
}

### Récupérer les places à partir d'un parkingId (Exemple ID 4)
GET {{baseUrl}}/api/place/getPlaceByParkingId/4
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Récupérer les places à partir d'un userId (Exemple ID 4)
GET {{baseUrl}}/api/place/getPlaceByUserId/2
Authorization: Bearer {{authToken}}
Content-Type: application/json


### --- DEMANDES PERMANANTES ---

### Créer une demande
POST {{baseUrl}}/api/demandePermanante
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "user": { "idUser": 1 },
  "entreprise": { "idEntreprise": 1 },
  "place": { "idPlace": 55 }
}

### Accepter une demande (ID 1)
PATCH {{baseUrl}}/api/demandePermanante/3/accepter
Authorization: Bearer {{authToken}}

### Refuser une demande (ID 1)
PATCH {{baseUrl}}/api/demandePermanante/1/refuser
Authorization: Bearer {{authToken}}

### Récupérer TOUTES les demandes permanantes (ALL)
GET {{baseUrl}}/api/demandePermanante/all
Authorization: Bearer {{authToken}}

### Récupérer les demandes permanantes d'une entreprise (Exemple ID 1)
GET {{baseUrl}}/api/demandePermanante/entreprise/1
Authorization: Bearer {{authToken}}

### Récupérer les demandes permanantes d'un user (Exemple ID 1)
GET {{baseUrl}}/api/demandePermanante/user/2
Authorization: Bearer {{authToken}}

### --- PERIODES DISPO ---

### Ajouter une période de disponibilité
POST {{baseUrl}}/api/periodes
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "start": "2026-04-01T08:00:00",
  "end": "2026-04-01T18:00:00",
  "place": { "idPlace": 55 }
}

### Supprimer une période (ID 1)
DELETE {{baseUrl}}/api/periodes/1
Authorization: Bearer {{authToken}}

### Récupérer TOUTES les périodes de disponibilité (ALL)
GET {{baseUrl}}/api/periodes/all
Authorization: Bearer {{authToken}}

### Récupérer les périodes de dispo d'une entreprise (Exemple ID 1)
GET {{baseUrl}}/api/periodes/entreprise/1
Authorization: Bearer {{authToken}}